"""Initial tables

Revision ID: 25caf1590184
Revises: 
Create Date: 2025-12-07 19:02:24.766122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25caf1590184'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification_year', sa.Integer(), nullable=False),
    sa.Column('health_exercise_manager', sa.Integer(), nullable=True),
    sa.Column('professional_sports_1', sa.Integer(), nullable=True),
    sa.Column('professional_sports_2', sa.Integer(), nullable=True),
    sa.Column('living_sports_1', sa.Integer(), nullable=True),
    sa.Column('living_sports_2', sa.Integer(), nullable=True),
    sa.Column('youth_sports', sa.Integer(), nullable=True),
    sa.Column('senior_sports', sa.Integer(), nullable=True),
    sa.Column('disabled_sports_1', sa.Integer(), nullable=True),
    sa.Column('disabled_sports_2', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_stats_id'), 'coach_stats', ['id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('facility_type_code', sa.String(length=20), nullable=True),
    sa.Column('facility_type_name', sa.String(length=100), nullable=True),
    sa.Column('industry_code', sa.String(length=20), nullable=True),
    sa.Column('industry_name', sa.String(length=100), nullable=True),
    sa.Column('region_sido_code', sa.String(length=20), nullable=True),
    sa.Column('region_sido', sa.String(length=50), nullable=True),
    sa.Column('region_sigungu_code', sa.String(length=20), nullable=True),
    sa.Column('region_sigungu', sa.String(length=50), nullable=True),
    sa.Column('emd_code', sa.String(length=20), nullable=True),
    sa.Column('emd_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facilities_region', 'facilities', ['region_sido', 'region_sigungu'], unique=False)
    op.create_index('idx_facilities_type', 'facilities', ['facility_type_name'], unique=False)
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_table('facility_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_ym', sa.String(length=10), nullable=False),
    sa.Column('region_sido_code', sa.String(length=20), nullable=True),
    sa.Column('region_sido', sa.String(length=50), nullable=True),
    sa.Column('region_sigungu_code', sa.String(length=20), nullable=True),
    sa.Column('region_sigungu', sa.String(length=50), nullable=True),
    sa.Column('facility_count', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('facility_per_person', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facility_stats_region', 'facility_stats', ['region_sido', 'region_sigungu'], unique=False)
    op.create_index(op.f('ix_facility_stats_id'), 'facility_stats', ['id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=200), nullable=True),
    sa.Column('facility_type_code', sa.String(length=20), nullable=True),
    sa.Column('facility_type_name', sa.String(length=100), nullable=True),
    sa.Column('industry_code', sa.String(length=20), nullable=True),
    sa.Column('industry_name', sa.String(length=100), nullable=True),
    sa.Column('region_sido_code', sa.String(length=20), nullable=True),
    sa.Column('region_sido', sa.String(length=50), nullable=True),
    sa.Column('region_sigungu_code', sa.String(length=20), nullable=True),
    sa.Column('region_sigungu', sa.String(length=50), nullable=True),
    sa.Column('emd_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('program_type', sa.String(length=100), nullable=True),
    sa.Column('program_name', sa.String(length=200), nullable=True),
    sa.Column('target_group', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('schedule_weekdays', sa.String(length=50), nullable=True),
    sa.Column('schedule_time', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_type', sa.String(length=50), nullable=True),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_programs_region', 'programs', ['region_sido', 'region_sigungu'], unique=False)
    op.create_index('idx_programs_target', 'programs', ['target_group'], unique=False)
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_table('support_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_year', sa.Integer(), nullable=False),
    sa.Column('region_sido_code', sa.String(length=20), nullable=True),
    sa.Column('region_sido', sa.String(length=50), nullable=True),
    sa.Column('region_sigungu_code', sa.String(length=20), nullable=True),
    sa.Column('region_sigungu', sa.String(length=50), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('facility_count', sa.Integer(), nullable=True),
    sa.Column('recipient_type_code', sa.String(length=10), nullable=True),
    sa.Column('recipient_type_name', sa.String(length=100), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_support_stats_region', 'support_stats', ['region_sido', 'region_sigungu'], unique=False)
    op.create_index('idx_support_stats_year', 'support_stats', ['base_year'], unique=False)
    op.create_index(op.f('ix_support_stats_id'), 'support_stats', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'parent', 'coach', 'official', name='userrole'), nullable=False),
    sa.Column('school_or_org', sa.String(length=200), nullable=True),
    sa.Column('region_sido', sa.String(length=50), nullable=True),
    sa.Column('region_sigungu', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('program', 'facility', 'coach', name='targettype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bookmarks_target', 'bookmarks', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_bookmarks_user', 'bookmarks', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('talent_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F', name='gender'), nullable=False),
    sa.Column('region_sido', sa.String(length=50), nullable=True),
    sa.Column('region_sigungu', sa.String(length=50), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('grip_strength', sa.Float(), nullable=True),
    sa.Column('sit_ups', sa.Integer(), nullable=True),
    sa.Column('standing_long_jump', sa.Float(), nullable=True),
    sa.Column('shuttle_run_20m', sa.Integer(), nullable=True),
    sa.Column('sit_and_reach', sa.Float(), nullable=True),
    sa.Column('cardio_endurance', sa.Float(), nullable=True),
    sa.Column('flexibility', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_talent_tests_region', 'talent_tests', ['region_sido', 'region_sigungu'], unique=False)
    op.create_index('idx_talent_tests_user_id', 'talent_tests', ['user_id'], unique=False)
    op.create_index(op.f('ix_talent_tests_id'), 'talent_tests', ['id'], unique=False)
    op.create_table('talent_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_test_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('grade_level', sa.Enum('high', 'medium', 'low', name='gradelevel'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['talent_test_id'], ['talent_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_talent_scores_sport', 'talent_scores', ['sport'], unique=False)
    op.create_index('idx_talent_scores_test_id', 'talent_scores', ['talent_test_id'], unique=False)
    op.create_index(op.f('ix_talent_scores_id'), 'talent_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_talent_scores_id'), table_name='talent_scores')
    op.drop_index('idx_talent_scores_test_id', table_name='talent_scores')
    op.drop_index('idx_talent_scores_sport', table_name='talent_scores')
    op.drop_table('talent_scores')
    op.drop_index(op.f('ix_talent_tests_id'), table_name='talent_tests')
    op.drop_index('idx_talent_tests_user_id', table_name='talent_tests')
    op.drop_index('idx_talent_tests_region', table_name='talent_tests')
    op.drop_table('talent_tests')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.drop_index('idx_bookmarks_user', table_name='bookmarks')
    op.drop_index('idx_bookmarks_target', table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_support_stats_id'), table_name='support_stats')
    op.drop_index('idx_support_stats_year', table_name='support_stats')
    op.drop_index('idx_support_stats_region', table_name='support_stats')
    op.drop_table('support_stats')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_index('idx_programs_target', table_name='programs')
    op.drop_index('idx_programs_region', table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_facility_stats_id'), table_name='facility_stats')
    op.drop_index('idx_facility_stats_region', table_name='facility_stats')
    op.drop_table('facility_stats')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_index('idx_facilities_type', table_name='facilities')
    op.drop_index('idx_facilities_region', table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_coach_stats_id'), table_name='coach_stats')
    op.drop_table('coach_stats')
    # ### end Alembic commands ###
