"""Add inquiry table and admin role

Revision ID: bac8fb47afd1
Revises: 9ee536e38dfe
Create Date: 2025-12-08 01:46:40.427773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac8fb47afd1'
down_revision: Union[str, None] = '9ee536e38dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add 'admin' to userrole enum
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'admin'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'answered', 'closed', name='inquirystatus'), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inquiries_created_at', 'inquiries', ['created_at'], unique=False)
    op.create_index('idx_inquiries_status', 'inquiries', ['status'], unique=False)
    op.create_index(op.f('ix_inquiries_id'), 'inquiries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inquiries_id'), table_name='inquiries')
    op.drop_index('idx_inquiries_status', table_name='inquiries')
    op.drop_index('idx_inquiries_created_at', table_name='inquiries')
    op.drop_table('inquiries')
    # ### end Alembic commands ###
